# $HOME/.k9s/hotkey.yml
hotKey:
  # Hitting Shift-1 navigates to your pod view
  shift-1:
    shortCut:    Shift-1
    description: Viewing pods
    command:     pods
  # Hitting Shift-2 navigates to your deployments
  shift-2:
    shortCut:    Shift-2
    description: View deployments
    command:     dp
  # Hitting Shift-3 navigates to your xray deployments
  shift-3:
    shortCut:    Shift-3
    description: Xray Deployments
    command:     xray deploy
