k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: k3s-default
  currentCluster: k3s-default
  clusters:
    k3s-default:
      namespace:
        active: local
        favorites:
        - local
        - all
        - default
      view:
        active: pods
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
